# Generated by Django 4.1.3 on 2022-12-01 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=300, verbose_name='Имя заказчика')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия заказчика')),
                ('patronymic', models.CharField(max_length=300, verbose_name='Отчество заказчика')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Номер телефона заказчика')),
                ('confirm_call', models.BooleanField(default=False, verbose_name='Звонок для подтверждения')),
                ('products_amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Количество товаров в заказе')),
                ('order_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Стоимость товара')),
                ('is_active', models.BooleanField(default=False, verbose_name='Заказ подтвержден')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='Products.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
