# Generated by Django 4.1.3 on 2022-12-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
