# Generated by Django 4.1.3 on 2022-12-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_order_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=300, verbose_name='Фамілія'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=300, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Замовлення сплачено?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна товару'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='кількість товару'),
        ),
    ]
