# Generated by Django 4.1.3 on 2023-01-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_alter_order_last_name_alter_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total price of item'),
        ),
    ]
