# Generated by Django 4.1.3 on 2023-01-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_order_order_total_price_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total_price',
            field=models.IntegerField(default=0, verbose_name='Order total price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_total_price',
            field=models.IntegerField(default=0, verbose_name='Total price of item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_total_price_view',
            field=models.CharField(blank=True, max_length=350, verbose_name='Item total price with normal view'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(verbose_name='Ціна товару'),
        ),
    ]
