# Generated by Django 4.1.3 on 2023-01-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_alter_order_order_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_total_price_view',
        ),
    ]
