# Generated by Django 4.1.3 on 2022-12-01 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Имя категории в ссылке')),
            ],
            options={
                'verbose_name': 'категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя подкатегории')),
                ('slug', models.SlugField(unique=True, verbose_name='Имя подкатегории в ссылке')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productcategory', verbose_name='Основная категория')),
            ],
            options={
                'verbose_name': 'подкатегория товаров',
                'verbose_name_plural': 'Подкатегории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя товара')),
                ('short_info', models.CharField(blank=True, max_length=2500, verbose_name='Короткая информация о товаре')),
                ('full_info', models.TextField(blank=True, verbose_name='Полная информация о товаре')),
                ('img', models.ImageField(blank=True, upload_to='products_images/', verbose_name='Фото товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость товара')),
                ('discount_availability', models.BooleanField(default=False, verbose_name='Наличие скидки')),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Скидка на товар (если есть)')),
                ('price_with_discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('article', models.CharField(blank=True, max_length=250, verbose_name='Артикул товара')),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.productcategory', verbose_name='Основная категория товара')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.productsubcategory', verbose_name='Подкатегория товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
