# Generated by Django 4.1.3 on 2022-12-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_price_with_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Have in shop', 'Есть в наличии'), ('Ends in shop', 'Заканчивается'), ('Not in shop', 'Нет в наличии')], default='Have in shop', max_length=300),
        ),
    ]
