# Generated by Django 4.1.3 on 2022-12-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='Products.productsubcategory', verbose_name='Подкатегории'),
        ),
    ]
