# Generated by Django 4.1.3 on 2022-12-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_productcategory_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='Products.productsubcategory', verbose_name='Подкатегории'),
        ),
    ]
