# Generated by Django 4.1.3 on 2022-12-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['id'], 'verbose_name': 'категорія товарів', 'verbose_name_plural': 'Категорії товарів'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name': 'підкатегорія товарів', 'verbose_name_plural': 'Підкатегорії товарів'},
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=250, verbose_name='Артикул товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, verbose_name='Знижка на товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_availability',
            field=models.BooleanField(default=False, verbose_name='Наявність знижки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_info',
            field=models.TextField(blank=True, verbose_name='Повна інформація про товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='products_images/', verbose_name='Фото товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.productcategory', verbose_name='Основна категорія товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name="Ім'я товару"),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Вартість товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Вартість товару зі знижкою'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_info',
            field=models.CharField(blank=True, max_length=2500, verbose_name='Коротка інформація про товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Have in shop', 'Є в наявності'), ('Ends in shop', 'Закінчується'), ('Not in shop', 'Нема в наявності')], default='Have in shop', max_length=300, verbose_name='Статус наявності товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.productsubcategory', verbose_name='Підкатегорія товару'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name="Ім'я категорії"),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name="Ім'я категорії в посиланні"),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='Products.productsubcategory', verbose_name='Підкатегорія'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productcategory', verbose_name='Основна категорія'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name="Ім'я подкатегории"),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name="Ім'я підкатегорії в посиланні"),
        ),
    ]
