# Generated by Django 4.1.3 on 2022-12-05 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0011_remove_product_short_info_product_characteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('review', models.TextField(verbose_name='Відклик')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата залишення відклику')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'відклик',
                'verbose_name_plural': 'Відклики',
                'ordering': ['-created_at'],
            },
        ),
    ]
