# Generated by Django 4.1.3 on 2022-12-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_alter_reviews_options_remove_reviews_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
    ]
