# Generated by Django 4.1.3 on 2022-12-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name="Ім'я категорії в заголовку сторінки"),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name="Ім'я підкатегорії в заголовку сторінки"),
        ),
    ]
