# Generated by Django 4.1.3 on 2022-12-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_product_price_view_product_price_with_discount_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Total rating of product'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='subcategory',
            field=models.ManyToManyField(blank=True, db_index=True, to='Products.productsubcategory', verbose_name='Підкатегорія'),
        ),
    ]
