# Generated by Django 4.1.3 on 2023-01-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_product_total_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=250, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
    ]
