# Generated by Django 4.1.3 on 2023-01-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_productcolorchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='colors', to='Products.productcolorchoice', verbose_name='Colors'),
        ),
        migrations.AlterField(
            model_name='productcolorchoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.product', verbose_name='Товар'),
        ),
    ]
