# Generated by Django 4.1.3 on 2023-01-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_product_colors_alter_productcolorchoice_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productcolorchoice',
            name='product',
        ),
        migrations.AddField(
            model_name='productcolorchoice',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.productcategory', verbose_name='Product Category'),
            preserve_default=False,
        ),
    ]
