# Generated by Django 4.1.3 on 2023-01-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorchoice',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Product Category'),
        ),
    ]
