# Generated by Django 4.1.3 on 2023-01-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0027_product_colors_productcolorchoice_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorchoice',
            name='background_color',
            field=models.CharField(blank=True, max_length=250, verbose_name='Button background color'),
        ),
    ]
