# Generated by Django 4.1.3 on 2023-01-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0028_productcolorchoice_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMemoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_size', models.CharField(blank=True, max_length=250, verbose_name='Size of memory')),
            ],
            options={
                'verbose_name': 'Product memory size',
                'verbose_name_plural': 'Product memory sizes',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='e_sim',
            field=models.BooleanField(default=False, verbose_name='E-sim or no'),
        ),
        migrations.AddField(
            model_name='productcolorchoice',
            name='color_template',
            field=models.CharField(default=1, max_length=250, verbose_name='Color name which user will see'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcolorchoice',
            name='color',
            field=models.CharField(max_length=250, verbose_name='Color name in admin panel'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_memory', to='Products.productmemorycategory', verbose_name='Product memory size'),
        ),
    ]
