# Generated by Django 4.1.3 on 2023-01-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0029_productmemorycategory_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEsimGlobalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Esim or global title')),
            ],
            options={
                'verbose_name': 'Product memory size',
                'verbose_name_plural': 'Product memory sizes',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='e_sim',
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='Products.productcolorchoice', verbose_name='Product color'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_esim_glob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_esim_glob', to='Products.productesimglobalcategory', verbose_name='Product esim or global'),
        ),
    ]
