# Generated by Django 4.1.3 on 2023-01-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0032_productcolorcategory_remove_product_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='Products.productcolorcategory', verbose_name='Product color'),
        ),
    ]
