# Generated by Django 4.1.3 on 2023-01-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0033_product_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Product version')),
            ],
            options={
                'verbose_name': 'Product version category',
                'verbose_name_plural': 'Product versions categories',
            },
        ),
        migrations.AlterModelOptions(
            name='productcolorcategory',
            options={'verbose_name': 'Color category', 'verbose_name_plural': 'Color categories'},
        ),
        migrations.AlterModelOptions(
            name='productmemorycategory',
            options={'verbose_name': 'Product memory size category', 'verbose_name_plural': 'Product memory sizes categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_esim_glob',
        ),
        migrations.RemoveField(
            model_name='productcolorchoice',
            name='esim_glob',
        ),
        migrations.DeleteModel(
            name='ProductEsimGlobalCategory',
        ),
    ]
