# Generated by Django 4.1.3 on 2023-01-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0034_productversion_alter_productcolorcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_esim_glob', to='Products.productversion', verbose_name='Product esim or global'),
        ),
        migrations.AddField(
            model_name='productcolorchoice',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productversion', verbose_name='Product esim or global'),
        ),
    ]
