# Generated by Django 4.1.3 on 2023-01-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0035_product_product_version_productcolorchoice_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolorchoice',
            options={'verbose_name': 'Color choice', 'verbose_name_plural': 'Colors choices'},
        ),
        migrations.AlterField(
            model_name='productcolorchoice',
            name='color',
            field=models.CharField(max_length=250, verbose_name='Color name at the choice button'),
        ),
        migrations.CreateModel(
            name='ProductMemoryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(max_length=250, verbose_name='Memory at the choice button')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productcolorcategory', verbose_name='Product color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_product', to='Products.product', verbose_name='Товар')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productversion', verbose_name='Product version')),
            ],
            options={
                'verbose_name': 'Memory choice',
                'verbose_name_plural': 'Memory choices',
            },
        ),
    ]
