# Generated by Django 4.1.3 on 2023-01-01 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0038_rename_productversionchoices_productversionchoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmemorychoice',
            options={'verbose_name': "Вибір розміру пам'яті", 'verbose_name_plural': "Вибір розмірів пам'яті"},
        ),
        migrations.AlterModelOptions(
            name='productversionchoice',
            options={'verbose_name': 'Вибір версії товару', 'verbose_name_plural': 'Вибір версій товару'},
        ),
        migrations.RemoveField(
            model_name='productmemorychoice',
            name='memory',
        ),
        migrations.AlterField(
            model_name='productmemorychoice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Підкатегорія товару'),
        ),
        migrations.AlterField(
            model_name='productmemorychoice',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productcolorcategory', verbose_name='Колір товару'),
        ),
        migrations.AlterField(
            model_name='productmemorychoice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний?'),
        ),
        migrations.AlterField(
            model_name='productmemorychoice',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productversion', verbose_name='Версія товару'),
        ),
        migrations.AlterField(
            model_name='productversionchoice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Підкатегорія товару'),
        ),
        migrations.AlterField(
            model_name='productversionchoice',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productcolorcategory', verbose_name='Колір товару'),
        ),
        migrations.AlterField(
            model_name='productversionchoice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна?'),
        ),
        migrations.AlterField(
            model_name='productversionchoice',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productmemorycategory', verbose_name="Обсяг пам'яті товару"),
        ),
        migrations.AlterField(
            model_name='productversionchoice',
            name='version',
            field=models.CharField(max_length=300, verbose_name='Версія товару'),
        ),
    ]
