# Generated by Django 4.1.3 on 2023-01-01 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0039_alter_productmemorychoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmemorychoice',
            name='memory',
            field=models.CharField(default=1, max_length=250, verbose_name='Memory at the choice button'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmemorychoice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productmemorychoice',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productcolorcategory', verbose_name='Product color'),
        ),
    ]
