# Generated by Django 4.1.3 on 2023-01-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0040_productmemorychoice_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmemorychoice',
            name='memory',
            field=models.CharField(blank=True, max_length=250, verbose_name='Memory at the choice button'),
        ),
    ]
