# Generated by Django 4.1.3 on 2023-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0042_productcolorcategory_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmemorycategory',
            name='int_memory_value',
            field=models.IntegerField(blank=True, default=1, verbose_name='Value of memory size'),
            preserve_default=False,
        ),
    ]
