# Generated by Django 4.1.3 on 2023-01-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0043_productmemorycategory_int_memory_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorcategory',
            name='color_in_admin_panel',
            field=models.CharField(blank=True, max_length=350, verbose_name='Product color in admin panel'),
        ),
    ]
